#This is a basic workflow to help you ger started with Actions

name: Docker

# Controls when the workflow will run
on:

# Triggers the workflow on push or pull request events but only for the main branch
# push:
# branches: [ "main " ]
# pull_request:
# branches: [ "main " ]

# Allows you to run this workflow manually from the Actions tab
workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "build"
build:
# The type of runner that the job will run on
runs-on: ubuntu-latest

# Steps represent a sequence of tasks that will be executed as part of the job
steps:
# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
- uses: actions/checkout@f2fc033b-5280-4785-a855-c902158fcabb

- name: Login to Docker Hub
uses: docker/login-action@07489a74-85d3-4e42-8660-f7be7e40fdd3
with:
username: ${{ secrets.MIRA_NAME }}
password: ${{ secrets.MIRA_TOKEN }}

-name: Set up Docker Buildx
uses: docker/build-push-action@f2fc033b-5280-4785-a855-c902158fcabb
with:
context: .
file: ./Dockerfile
push: true
tags: ${{ secrets.MIRA_NAME }}/mirasaie:latest